# Generated by Django 3.2.4 on 2021-06-28 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaVagaDesejada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('areaVagaDesejada', models.CharField(choices=[('FS', 'Full Stack'), ('FE', 'Front End'), ('BE', 'Back End')], default='FE', max_length=2)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'areaVagaDesejada',
                'verbose_name_plural': 'areasVagasDesejadas',
                'ordering': ('areaVagaDesejada',),
            },
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('objetivo', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('instagram', models.URLField()),
                ('teste', models.CharField(max_length=50)),
                ('fotoPerfil', models.ImageField(upload_to='curriculo/')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, unique=True, verbose_name='Slug')),
                ('areaVagaDesejada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculo.areavagadesejada')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'curriculo',
                'verbose_name_plural': 'curriculos',
                'ordering': ('nome',),
            },
        ),
    ]
