# Generated by Django 3.2.4 on 2021-06-28 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinguagensDominadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('linguagem', models.CharField(choices=[('Py', 'Python'), ('PHP', 'PHP'), ('Java', 'Java'), ('JS', 'JavaScript'), ('C', 'C'), ('C#', 'C#'), ('C++', 'C++'), ('Ruby', 'Ruby'), ('HTML', 'HTML'), ('CSS', 'CSS')], max_length=10)),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], max_length=10)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.curriculo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrameworkDominados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('frameworkDominado', models.CharField(choices=[('ANG', 'Angular'), ('NJS', 'Node.JS'), ('VUE', 'Vue'), ('EJS', 'Ember.js'), ('R', 'React'), ('EX', 'Express'), ('AJS', 'AdonisJs'), ('BTT', 'Bootstrap'), ('MTL', 'Materialize'), ('LRL', 'Laravel'), ('SPG', 'Spring'), ('DJG', 'Django'), ('ROR', 'RubyOnRails'), ('ANM', 'ASP.NET MVC')], max_length=10)),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], max_length=10)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.curriculo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=1000)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.curriculo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataBaseDominadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('database', models.CharField(choices=[('MSS', 'Microsoft SQL Server'), ('OR', 'Oracle RDBMS'), ('DB2', 'DB2'), ('MA', 'Microsoft Access'), ('MS', 'MySQL'), ('PO', 'PHP'), ('MDB', 'MongoDB')], max_length=10)),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], max_length=10)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.curriculo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
