# Generated by Django 3.2.4 on 2021-06-28 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_databasedominadas_experienciaprofissional_frameworkdominados_linguagensdominadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculo',
            name='areaVagaDesejada',
        ),
        migrations.DeleteModel(
            name='AreaVagaDesejada',
        ),
    ]
