# Generated by Django 3.2.4 on 2021-06-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0003_auto_20210628_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculo',
            name='teste',
        ),
    ]
